spring:
  application:
    name: efficent
  datasource:
    url: jdbc:postgresql://localhost:5432/efficent
    username: efficent
    password: ''
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: '*'
